# Docs: https://pnpm.io/settings
# https://github.com/emberjs/rfcs/pull/907

autoInstallPeers: false
resolvePeersFromWorkspaceRoot: false

verifyDepsBeforeRun: install

# silence missing peer warnings from vitepress's internal algolia deps
peerDependencyRules:
  ignoreMissing:
    - search-insights

# only allow these packages to run install scripts (postinstall, etc.)
onlyBuiltDependencies:
  - content-tag
  - esbuild

packages:
  - vite-plugin-ember
  - docs
