# Docs: https://pnpm.io/settings
# https://github.com/emberjs/rfcs/pull/907

autoInstallPeers: false
resolvePeersFromWorkspaceRoot: false

verifyDepsBeforeRun: install

# silence missing peer warnings from vitepress's internal algolia deps
peerDependencyRules:
  ignoreMissing:
    - search-insights

packages:
  - ember-live-compiler
  - vite-plugin-ember
  - docs

allowBuilds:
  esbuild: false

minimumReleaseAgeExclude:
  - '@glint/ember-tsc@1.8.6'
  - vite@8.1.2
